### ISSUE TITLE
贵站评论系统似乎未能生效，似乎是 giscus 的问题。

### ISSUE THREAD

**Issue by kaffa** [tsurumi-yizhou/blog#1]
https://giscus.app/api/discussions?repo=blog&term=%E5%8E%86%E5%8F%B2%E7%9A%84%E6%B6%88%E4%BA%A1&category=Announcements&number=0&strict=true&last=15

**Comment by tsurumi-yizhou** [comment]
经测试，更改配置后，在典型网络环境下，评论已可正常工作。感谢您的通知。
