### ISSUE TITLE
首页 css 404

### ISSUE THREAD

**Issue by chesha1** [tsurumi-yizhou/blog#2]
访问[首页](https://blog.yizhou.ac.cn/)的时候，样式没加载出来，看上去是 
https://blog.yizhou.ac.cn/_astro/about.DtzFgL0B.css 报了 404

<img width="995" alt="image" src="https://github.com/user-attachments/assets/3efabc29-dcbb-472c-a64f-50c070a23680">

**Comment by tsurumi-yizhou** [comment]
这个是之前的缓存了吧？现在的首页样式已经更改了。姑且在CDN里刷新了一下，虽然更改理应早就生效了才对。你这是什么网络环境？

**Comment by tsurumi-yizhou** [comment]
![截屏2024-12-10 17 15 33](https://github.com/user-attachments/assets/36c0ab1e-30d3-415c-bb30-9cacdf52c6f0)

**Comment by chesha1** [comment]
上图里，F12 是开了停用缓存的

现在能访问到了
